### ISSUE TITLE
Currency Format & Date Format always empty

### ISSUE THREAD

**Issue by darrentaytay** [Jorijn/ynab-sdk-php#2]
Hi @Jorijn 

Thank you for the SDK, it's been of great value to me.

I have a little issue when pulling in budgets that within the `BudgetSummary` classes, `dateFormat` & `currencyFormat` are always empty and return nothing.

If you could point me in the right direction, I'd be happy to raise a pull request to sort the issue out.

**Comment by jorijn** [comment]
Hi @dtisgodsson 

You generally shouldn't touch code generated by the swagger binary. I'd suggest you take a look at the JSON file and see if you can tweak some things there to make the swagger binary generate better code. Have a go at it at let me know if it works. If not, I'll try and make some time by the end of the week to get this sorted out.

Jorijn

**Comment by darrentaytay** [comment]
Cheers @Jorijn 

I'll have a look at the JSON and see what I can do.

Darren

**Comment by darrentaytay** [comment]
Good morning @Jorijn,

Just wanted to give you an update.

I'm not very clued up on on Swagger but I did some investigation into it but from what I can tell, your json file looks fine, the `$ref` to the `CurrencyFormat` definition and `DateFormat` from within the `BudgetSummary` definition look fine to me so I'm really not sure what the issue is.

I think to bridge this problem, I'll just need to CURL the API for now until we can perhaps talk about a fix in the future.

Cheers for your time!

Darren
